# Generated by Django 2.2.1 on 2019-05-31 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(null=True)),
                ('comment', models.TextField(default='Last Strike comment doesn´t be found', max_length=100)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes_given', to=settings.AUTH_USER_MODEL)),
                ('reported_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('when', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='debs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
